export const apartmentPlaces = [
  "Giedre Apartments - Kalnieciu 219",
  "Giedre Apartments - Kalnieciu 196",
  "Giedre Apartments - Taikos",
  "Giedre Apartments - Varniu",
  "Giedre Apartments - Nemuno",
  "Giedre Apartments - Puodziu",
  "Giedre Apartments - Linkuvos",
];
export const properties = [
  {
    title: "Kalniečių g. 219",
    id: "kalnieciu219/",
    description: "Atsipalaiduokite su visa šeima šioje ramioje vietoje...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/kalnieciu219/20240815_132619.jpg",
    ],
    price: 50,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Kalnieciu 219",
    loc: { lat: 54.92018789999999, lng: 23.9317768 },
  },
  {
    title: "Kalniečių g. 196 (1)",
    id: "kalnieciu196(1)/",
    description: "Pėstute iki Kauno Klinikų!...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/kalnieciu196(1)/20240420_113625.jpg",
    ],
    price: 50,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Kalnieciu 196",
    loc: null,
  },
  {
    title: "Kalniečių g. 196 (2)",
    id: "kalnieciu196(2)/",
    description: "Pėstute iki Kauno Klinikų!...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/kalnieciu196(2)/20240420_132045.jpg",
    ],
    price: 45,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Kalnieciu 196",
    loc: null,
  },
  {
    title: "Taikos pr. 33B",
    id: "taikospr33b/",
    description: "Šviesūs ir erdvūs 2iejų kambarių apartamentai...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/taikospr33b/01.jpg",
    ],
    price: 50,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Taikos",
    loc: { lat: 54.9126309, lng: 23.9492744 },
  },
  {
    title: "Varnių g. 24",
    id: "varniu24/",
    description: "Dideli ir erdvūs 2iejų kambarių apartamentai...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/varniu24/0.jpg",
    ],
    price: 50,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Varniu",
    loc: { lat: 54.9147724, lng: 23.8931991 },
  },
  {
    title: "Nemuno g. 22",
    id: "nemuno22/",
    description: "Nuomojami 2-ju kambariu apartamentai pačioje senamieščio...",
    images: ["https://gapartments.s3.eu-north-1.amazonaws.com/nemuno22/1.jpg"],
    price: 60,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Nemuno",
    loc: { lat: 54.89610080000001, lng: 23.8988133 },
  },
  {
    title: "Puodžių g. 27",
    id: "puodziu27/",
    description: "Nuomojama studija per 2 aukštus su kiemeliu rytinei kavai!...",
    images: ["https://gapartments.s3.eu-north-1.amazonaws.com/puodziu27/1.jpg"],
    price: 45,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Puodziu",
    loc: { lat: 54.8947349, lng: 23.9007687 },
  },
  {
    title: "Linkuvos g. 55",
    id: "linkuvos55/",
    description: "Butukas su atskiru įėjimu pirmame aukšte!...",
    images: [
      "https://gapartments.s3.eu-north-1.amazonaws.com/linkuvos55/20240625_134736.jpg",
    ],
    price: 40,
    add: ["2 kamb.", "4", "WiFi"],
    placeId: "Giedre Apartments - Linkuvos",
    loc: { lat: 54.9121773, lng: 23.88813 },
  },
];
